spring:
  datasource:
    password: Friew5la
    url: jdbc:mysql://localhost:3306/servermanager
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true